springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
    operationsSorter: method

server:
  servlet:
    context-path: /api/v2

spring:
  application:
    name: api-election
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    defer-datasource-initialization: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/eleicaoteste
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver